# Generated by Django 4.1.4 on 2023-01-03 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=256, verbose_name="Title")),
                ("discription", models.TextField(blank=True, null=True, verbose_name="Body")),
                ("deleted", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="InMenu",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=256, verbose_name="Title")),
                ("discription", models.TextField(blank=True, null=True, verbose_name="Body")),
                ("deleted", models.BooleanField(default=False)),
                ("menu", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="mainapp.menu")),
            ],
        ),
    ]
