# Generated by Django 4.1.4 on 2023-01-03 13:25

from django.db import migrations
def forwards_func(apps, schema_editor):
# Get model
    Menu = apps.get_model("mainapp", "Menu")
    # Create model's objects
    Menu.objects.create(
        title="Products",
        discription="Name of products"

    )
    Menu.objects.create(
        title="Technic",
        discription="Name of technic"
    )

def reverse_func(apps, schema_editor):
# Get model
    
    Menu = apps.get_model("mainapp", "Menu")

# Delete objects
    Menu.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
