# Generated by Django 4.1.4 on 2023-01-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_mainmenu_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmenu',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
