# Generated by Django 4.1.4 on 2023-01-06 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0008_alter_mainmenu_parent"),
    ]

    operations = [
        migrations.DeleteModel(
            name="InMenu",
        ),
        migrations.DeleteModel(
            name="Menu",
        ),
    ]
